pairs_path: ../data/2d/evp_1200itr_ts_dr710o_1ts_19760101_19760101_icemod_subset.nc
cache_path: ../data/cache/weddell-01.nc

parameters: ../configs/parameters/nn_2d.yaml
results_path: ../results/nn/2d/stencil5_2/
architecture: ../configs/nn_architecture/2d/stencil5_2.yaml

save_model: True
save_data: True

train_features: ['siconc', 'sithic', 'sivelv', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
train_labels: ['sivel_mag', 'sivel_u', 'sivel_v']
vectors:
  sivel: ['sivelv', 'sivelu']
  tau_ai: ['utau_ai', 'vtau_ai']
  tau_oi: ['utau_oi', 'vtau_oi']

zarr_fmt: 2d
difference_labels: False

scaling:
  std: ['siconc', 'sithic', 'sivel_mag', 'tau_ai_mag', 'tau_oi_mag']
scale_factor: 20

val_fraction: 0.2
test_fraction: 0.1

batch_size: 12
patch_size: 32
patches_per_image: 20

attr_baseline: 100
attr_samples: 10000
attr_batch_size: 1
hemisphere: south
